### ISSUE TITLE
twofishes.net web site needs updates

### ISSUE THREAD

**Issue by steveha-ziprecruiter** [foursquare/fsqio#12]
The twofishes.net web site still links to the now-obsolete "twofishes" repo on GitHub.  It should be edited to point to the new "fsqio" repo.

Also, the prebuilt Twofishes .jar file is very old, and should be updated with a recent build.  There is a bug in autocomplete that was fixed in Twofishes 0.90.3 that is still present in the prebuilt Twofishes .jar file, and a new build would include the fix.

**Comment by mateor** [comment]
This twofishes site is a bit of a legacy holdover. We recognize that it can be a bit confusing to consumers but don't have a great solution as of yet. I will leave your ticket open but I don't know if this will change anytime soon, sadly.

**Comment by mateor** [comment]
I am going to close this, we have decided to let the twofishes website go down.
