### ISSUE TITLE
twofishes looking for mongo in dependencies/mongodb/bin/mongo

### ISSUE THREAD

**Issue by blackmad** [foursquare/fsqio#15]
but pants doesn't seem to download it to there - is there some advised way in the fsqio workflow to get it there?

**Comment by rahulpratapm** [comment]
Hey David. That check shouldn't be in there. I'm going to take it out. All you need is a running mongo instance and you're good.

**Comment by rahulpratapm** [comment]
Pushed the change. It should propagate here shortly.

**Comment by mateor** [comment]
f52a9a516855c5f1a627114480fc9e54894eff3d

Thanks Rahul!
