### ISSUE TITLE
Add Outcome monad to fsqio?

### ISSUE THREAD

**Issue by omerzach** [foursquare/fsqio#16]
Hey there,

It'd be awesome to have Foursquare's Outcome class available for use in this repository. If I recall correctly it had few internal dependencies, so I imagine it'd be pretty straightforward to open source.

Thanks in advance!

**Comment by mateor** [comment]
Hi @omerzach. Always nice to hear from the user base 😉 

We discussed this and it seems like it would be a good thing for Foursquare to do. I will be the point person for it and will take a look this weekend.

**Comment by omerzach** [comment]
❤️ ❤️ ❤️
