### ISSUE TITLE
Docker image update?

### ISSUE THREAD

**Issue by wulftone** [foursquare/fsqio#18]
In reference to https://github.com/foursquare/fsqio/issues/17, we discovered that the docker image is probably out-of-date and fresh builds don't include changes that allow the map tiles to render properly.  This ticket is to track updating the docker image.

**Comment by mateor** [comment]
Thanks for opening the new issue. Dockerhub is configured to republish new images - but the build OOM-ed at one point some time ago and never retried.

I will look into getting that image builder working again and setting up some alerts for build failures.

**Comment by mateor** [comment]
I have restarted the Dockerhub build hooks. So the [`fsqio/fsqio`](https://hub.docker.com/r/fsqio/fsqio/) image has been published at the current HEAD of this repo. That build also triggered the downstream Dockerhub build for [`twofishes`](https://hub.docker.com/r/fsqio/twofishes) as well, so theorectically you should be able to run:

        docker pull fsqio/twofishes

and get the latest geocoder. We will have to just wait and see about the ongoing health of the build hooks. Feel free to open another issue if you see your image is stale.

As a final note, the Dockerfile for the `fsqio/fsqio` base image is also [included in this repo](https://github.com/foursquare/fsqio/blob/master/Dockerfile), you can update or rebuild that as needed.
