### ISSUE TITLE
Installing tag validation on a new repo

### ISSUE THREAD

**Issue by toddgardner** [foursquare/fsqio#30]
Took a stab at this also, seems straight forward.

Copy these files from the foursquare/fsqio repo to your repo:

```
src/python/fsqio/__init__.py
src/python/fsqio/pants/__init__.py
src/python/fsqio/pants/register.py
src/python/fsqio/pants/validate.py
```

Add a:

```
 [GLOBAL]
pythonpath: +[
    "%(buildroot)s/src/python",
  ]
backend_packages: +[
    "pants.contrib.node",
    "pants.contrib.python.checks",
    "fsqio.pants",
  ]

[tag]
by_prefix:  {
    "3rdparty": ["exempt"],
    "tests": ["tests"],
    "src": ["dependencies_cannot_have:tests"]
  }
```

**Comment by mateor** [comment]
I could possibly publish the tag backend separately.

I am going to try and find some time to figure out how to publish the plugins from Fsq.io. That would make this a lot saner, and also enable users to tweak and republish locally if necessary.

**Comment by mateor** [comment]
I moved this into its own plugin (not published to Pypi though) and wrote up these as a README. Thanks Todd!
