### ISSUE TITLE
Twofishes does not seem to recognize streets nor housenumbers at all

### ISSUE THREAD

**Issue by linuzer** [foursquare/fsqio#48]
Hi,
I installed twofishes with a wold-download following the install instructions. 
The geocoder is running and resolves villages, cities, named places around the world, but does not recognize any streetnames, nor housenumbers.

What could have gone wrong during installation? How can I find out? And how can I correct it?

Thanks for any help!

**Comment by mateor** [comment]
Hi - I know that this is an old issue. The geo team at Foursquare doesn't have the bandwidth to provide support for twofishes. I am sorry for essentially throwing this code over the wall, but I want to be upfront that support isn't possible for us at this time.
