### ISSUE TITLE
http://twofishes.net/ appears to be down

### ISSUE THREAD

**Issue by matkoniecz** [foursquare/fsqio#66]
It is linked from https://github.com/foursquare/fsqio/tree/master/src/jvm/io/fsq/twofishes

Note to self: if twofishes is actually alive then please revert me at https://wiki.openstreetmap.org/wiki/Search_engines#Search_engine_software and mark it as alive project

**Comment by mateor** [comment]
This repo is alive, and runs as described in the README in the root. I can easily imagine a documentation issue, although not sure what problem you are having without details or repro.

Having said that, users are mostly expected to unblock themselves. Fsq.io is used by production at Foursquare and offered here without guaranteed support

**Comment by matkoniecz** [comment]
> Prebuilt indexes and binaries available at twofishes.net.

**Comment by stouch** [comment]
👀

**Comment by YassineALLAL** [comment]
> not sure what problem you are having without details or repro.

```
yassine@computer:~$ curl --connect-timeout 10 http://twofishes.net/
curl: (28) Connection timeout after 10001 ms
```
I hope it's clear.

**Comment by stouch** [comment]
@YassineALLAL  https://github.com/foursquare/fsqio/issues/72#issuecomment-1164853514 

> while we still use twofishes internally at Foursquare, it hasn't been under active development for quite some time and it's unclear if we'll be picking it back up any time soon

**Comment by matkoniecz** [comment]
note: I removed it from https://wiki.openstreetmap.org/wiki/Geocoding#Open_source_geocoders
