### ISSUE TITLE
An updated prebuilt ?

### ISSUE THREAD

**Issue by stouch** [foursquare/fsqio#72]
I am looking for an updated pre-built (the world geonames have changed a lot since 2015 ! :))

twofishes.net seems down since few months.

Thanks!

**Comment by jvandew** [comment]
Hello!

Unfortunately we don't have any plans to release a new set of pre-built indexes for the time being -- while we still use twofishes internally at Foursquare, it hasn't been under active development for quite some time and it's unclear if we'll be picking it back up any time soon.

Apologies for not having a better answer for you... we expect to have a more concrete direction for it in the coming months.

**Comment by stouch** [comment]
Thank you, 
I recently tried to make a fresh build of it inside a docker of `fsqio/fsqio`, using : 
```/src/jvm/io/fsq/twofishes/parse.py --output_revgeo_index --output_prefix_index --output_s2_covering_index``` 
(like in the 2015-03-05.zip index)

But it stayed stuck forever while [ivy-resolve] 

I don't know if it is still possible to build it manually. If yes, I could re-build a new one and share it to you guys.

Regards,

**Comment by missinglink** [comment]
You might also consider placeholder: https://geocode.earth/blog/2019/almost-one-line-coarse-geocoding

**Comment by jvandew** [comment]
> But it stayed stuck forever while [ivy-resolve]

that is just a very slow step the first time you run it, there is quite a lot of caching that happens behind the scenes to make it relatively quick on subsequent runs

**Comment by stouch** [comment]
For the record, I finally used https://github.com/pelias
