### ISSUE TITLE
Add HFileV1 reader/writer code to fsqio

### ISSUE THREAD

**Issue by slackhappy** [foursquare/fsqio#8]
Hello my fine friends!

I'm interested in using quiver at Slack, and I've hacked together the HFileV1 HFileOutputFormat with direct key value pairs on top of hbase 0.94, but as you can imagine, relying on that is a bit unpopular.

I remember that some of this code was reimplemented outside of hbase to avoid the legacy dep.  Could we include it here?  There is a real dearth of MR-writable file formats out there with an associated static server.

This is a whiskey-bounty eligible request.

<3
johng

**Comment by mateor** [comment]
Hi @slackhappy. The common consensus is that Foursquare is willing to do that.  We will be taking a look at how much work that may/may not be soonish.

**Comment by tdyas** [comment]
<img width="102" alt="screen shot 2016-05-10 at 6 05 29 pm" src="https://cloud.githubusercontent.com/assets/901363/15163986/dd9569a0-16d9-11e6-840c-0434f89e9826.png">

**Comment by slackhappy** [comment]
It'll be okay, broken heart, we can still be friends.

**Comment by mateor** [comment]
Hi @slackhappy. Hope you are well.

Foursquare open sourced the HFile Reader and Writer code today, thanks to @theevocater who did all the work :)

8a6ff0075aae5cc05347ed43e0e84859b1d31c7c
e3ecb932172c35ed237b4f36a7cd7a77c064180f
856167995f021a5ed9995a4302204b7ff96cb809
f1b8127531531cecf15a9316b9ffec7552d08de4

Hope that you find it useful!
