### ISSUE TITLE
Add a CI setup to give contributors a prayer at making a sane contribution.

### ISSUE THREAD

**Issue by jsirois** [foursquare/fsqio#9]
A `.travis.yml` for example + enabling the travis hook for this repo would be great.

**Comment by mateor** [comment]
I have picked this up. We are pretty close, but Travis is [currently barfing on the Thrift-generated scala](https://travis-ci.org/mateor/fsqio/builds/132981798).

We have Fsqio on Jenkins internally but it has long been on the TODO list to create a public facing CI, so thanks for the nudge.

**Comment by mateor** [comment]
note: I am running these tests [out of a fork](https://github.com/mateor/fsqio/tree/mongo_repro) for iteration purposes.

**Comment by mateor** [comment]
Travis CI build is up and green: bfc48873a792d168ee9293e39a1125528417912f

I was pretty close to giving up on this - but I got it unblocked at the buzzer. Almost all of the trouble was getting JDK 8 and our heavy-weight codegen to reliably run under the constraints of Travis CI - the repo itself was indeed buildable/testable as long as the requirements were available.
